# Generated by Django 5.0.1 on 2024-01-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='DALILI1',
            field=models.PositiveIntegerField(choices=[(1, 'Kidonda sehemu za siri'), (0, 'Hakuna dalili')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DALILI2',
            field=models.PositiveIntegerField(choices=[(1, 'Kutoa uchafu sehemu za siri'), (0, 'Hakuna dalili')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DALILI3',
            field=models.PositiveIntegerField(choices=[(1, 'Maumivu tumbo la chini'), (0, 'Hakuna dalili')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DALILI4',
            field=models.PositiveIntegerField(choices=[(1, 'Kuwashwa sehemu za siri'), (0, 'Hakuna dalili')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='DALILI5',
            field=models.PositiveIntegerField(choices=[(1, 'Maumivu wakati au baada ya kukojoa'), (0, 'Hakuna dalili')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='MAAMBUKIZI',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='sex',
            field=models.CharField(choices=[(1, 'Me'), (0, 'Ke')]),
        ),
    ]
