# Generated by Django 5.0.1 on 2024-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_task_dalili1_task_dalili2_task_dalili3_task_dalili4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='MAAMBUKIZI',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, 'Me'), (0, 'Ke')]),
        ),
    ]
