# Generated by Django 5.0.1 on 2024-01-14 11:13

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_task_maambukizi_alter_task_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Patient_Id',
            field=models.CharField(db_index=True, default=clinic.models.generate_random_code, max_length=9),
        ),
    ]
