# Generated by Django 5.0.1 on 2024-01-14 11:43

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_task_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Patient_Id',
            field=models.CharField(db_index=True, default=clinic.models.generate_random_code, editable=False, max_length=9),
        ),
    ]
