# Generated by Django 5.0.1 on 2024-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_task_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Patient_Id',
            new_name='Namba_ya_mgonjwa',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='address',
            new_name='anwani',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='email',
            new_name='jina_la_kwanza',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='jina_la_mtumiaji',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='firstname',
            new_name='jina_la_pili',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='sex',
            new_name='jinsia',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='secondname',
            new_name='simu',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='age',
            new_name='umri',
        ),
        migrations.AlterField(
            model_name='task',
            name='DALILI1',
            field=models.PositiveIntegerField(choices=[(1, 'Kidonda sehemu za siri'), (0, 'Hakuna dalili')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='DALILI2',
            field=models.PositiveIntegerField(choices=[(1, 'Kutoa uchafu sehemu za siri'), (0, 'Hakuna dalili')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='DALILI3',
            field=models.PositiveIntegerField(choices=[(1, 'Maumivu tumbo la chini'), (0, 'Hakuna dalili')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='DALILI4',
            field=models.PositiveIntegerField(choices=[(1, 'Kuwashwa sehemu za siri'), (0, 'Hakuna dalili')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='DALILI5',
            field=models.PositiveIntegerField(choices=[(1, 'Maumivu wakati au baada ya kukojoa'), (0, 'Hakuna dalili')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
