# Generated by Django 5.0.1 on 2024-02-01 16:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_rename_patient_id_task_namba_ya_mgonjwa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Patient',
        ),
    ]
