# Generated by Django 5.0.1 on 2024-02-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitals',
            field=models.CharField(choices=[(1, 'Tengeru'), (2, 'Selian'), (3, 'NSK'), (4, 'St. Elizabeth'), (5, 'AICC'), (6, 'Mount Meru'), (7, 'St. Joseph')], default=1),
        ),
    ]
