# Generated by Django 5.0.1 on 2024-02-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_hospital_hospitals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
