# Generated by Django 5.0.1 on 2024-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_delete_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospitali',
            field=models.PositiveIntegerField(choices=[(1, 'Tengeru'), (2, 'Selian'), (3, 'NSK'), (4, 'St. Elizabeth'), (5, 'AICC'), (6, 'Mount Meru'), (7, 'St. Joseph')], default=1),
        ),
    ]
