# Generated by Django 5.0.1 on 2024-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_patient_hospitali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospitali',
            field=models.CharField(choices=[('Tengeru', 'Tengeru'), ('Selian', 'Selian'), ('NSK', 'NSK'), ('St. Elizabeth', 'St. Elizabeth'), ('AICC', 'AICC'), ('Mount Meru', 'Mount Meru'), ('St. Joseph', 'St. Joseph')], default='Tengeru'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='jinsia',
            field=models.CharField(choices=[('Me', 'Me'), ('Ke', 'Ke')]),
        ),
    ]
