# Generated by Django 5.0 on 2024-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0012_alter_patient_hospitali_alter_patient_jinsia"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="tarehe",
            field=models.DateField(blank=True, null=True),
        ),
    ]
