# Generated by Django 5.0 on 2024-08-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0014_alter_patient_tarehe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jina_la_pili", models.CharField(blank=True, null=True)),
                ("umri", models.PositiveIntegerField(blank=True, null=True)),
                ("anwani", models.TextField(blank=True, null=True)),
                ("Uchunguzi", models.TextField(blank=True, null=True)),
                (
                    "jina_la_kwanza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.patient",
                    ),
                ),
            ],
        ),
    ]
