# Generated by Django 5.0 on 2024-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0014_alter_patient_tarehe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AlterField(
            model_name="patient",
            name="hospitali",
            field=models.CharField(
                choices=[
                    ("Tengeru", "Tengeru"),
                    ("Nambala", "Nambala"),
                    ("Kikwe", "Kikwe"),
                    ("Moshi", "Moshi"),
                    ("Arusha", "Arusha"),
                    ("Usa River", "Usa River"),
                    ("Kikatiti", "Kikatiti"),
                ],
                default="Tengeru",
            ),
        ),
    ]
