# Generated by Django 5.0 on 2024-09-11 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0015_alter_patient_options_alter_patient_hospitali"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="complete",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="created",
        ),
    ]
