# Generated by Django 5.0 on 2024-08-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0015_alter_patient_options_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="jina_la_kwanza",
            field=models.CharField(blank=True, null=True),
        ),
    ]
