# Generated by Django 5.0 on 2024-09-11 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0016_remove_patient_complete_remove_patient_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
